version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080 